const businessCardLayoutJSON = [
    {
        "productTitle": "Business Card Slim - Layouts",
        "title": "white",
        "thumbnail": "/Bildschirmfoto-2018-02-11-um-22.21.01.png",
        "options": {
            "stageWidth": 1100,
            "stageHeight": 800,
            "customAdds": {
                "uploads": true,
                "texts": true,
                "designs": true
            }
        },
        "mask": {
            "url": "/mask.svg",
            "left": "125",
            "top": "125"
        },
        "elements": [
            {
                "title": "Base",
                "source": "/BC-base-2.png",
                "type": "image",
                "parameters": {
                    "left": 550,
                    "top": 400,
                    "originX": "center",
                    "originY": "center",
                    "z": -1,
                    "fill": false,
                    "colorLinkGroup": false,
                    "draggable": false,
                    "rotatable": false,
                    "resizable": false,
                    "removable": false,
                    "flipX": false,
                    "flipY": false,
                    "zChangeable": false,
                    "scaleX": 1,
                    "scaleY": 1,
                    "lockUniScaling": false,
                    "uniScalingUnlockable": false,
                    "angle": 0,
                    "price": 0,
                    "autoCenter": false,
                    "replaceInAllViews": false,
                    "autoSelect": false,
                    "topped": false,
                    "boundingBoxMode": "inside",
                    "opacity": 1,
                    "excludeFromExport": false,
                    "locked": false,
                    "showInColorSelection": false,
                    "boundingBox": "",
                    "resizeToW": "0",
                    "resizeToH": "0",
                    "scaleMode": "fit",
                    "minScaleLimit": 0.01,
                    "advancedEditing": false,
                    "uploadZone": false,
                    "uploadZoneMovable": false,
                    "customAdds": []
                }
            },
            {
                "title": "background",
                "source": "/background.png",
                "type": "image",
                "parameters": {
                    "left": 550,
                    "top": 400,
                    "originX": "center",
                    "originY": "center",
                    "z": -1,
                    "fill": false,
                    "colors": "#000000, #ff0000, #008080, #0000ff, #800080",
                    "colorLinkGroup": false,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "removable": true,
                    "flipX": false,
                    "flipY": false,
                    "zChangeable": false,
                    "scaleX": 1,
                    "scaleY": 1,
                    "lockUniScaling": false,
                    "uniScalingUnlockable": false,
                    "angle": 0,
                    "price": 0,
                    "autoCenter": false,
                    "replaceInAllViews": false,
                    "autoSelect": false,
                    "topped": false,
                    "boundingBoxMode": "clipping",
                    "opacity": 1,
                    "excludeFromExport": false,
                    "locked": false,
                    "showInColorSelection": false,
                    "boundingBox": "",
                    "resizeToW": "0",
                    "resizeToH": "0",
                    "scaleMode": "fit",
                    "minScaleLimit": 0.01,
                    "advancedEditing": false,
                    "uploadZone": false,
                    "uploadZoneMovable": false,
                    "customAdds": []
                }
            },
            {
                "title": "COMPANY NAME",
                "source": "COMPANY NAME",
                "type": "text",
                "parameters": {
                    "left": 550,
                    "top": 400,
                    "originX": "center",
                    "originY": "center",
                    "z": -1,
                    "fill": "#ffffff",
                    "colors": "#000000",
                    "colorLinkGroup": false,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "removable": true,
                    "flipX": false,
                    "flipY": false,
                    "zChangeable": false,
                    "scaleX": 1,
                    "scaleY": 1,
                    "lockUniScaling": true,
                    "uniScalingUnlockable": false,
                    "angle": 0,
                    "price": 0,
                    "autoCenter": false,
                    "replaceInAllViews": false,
                    "autoSelect": false,
                    "topped": false,
                    "boundingBoxMode": "clipping",
                    "opacity": 1,
                    "excludeFromExport": false,
                    "locked": false,
                    "showInColorSelection": false,
                    "boundingBox": "Base",
                    "fontFamily": "Ostrich",
                    "fontSize": 98,
                    "editable": true,
                    "lineHeight": 1,
                    "textDecoration": "normal",
                    "maxLength": 0,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textAlign": "left",
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "stroke": "#ffffff",
                    "strokeWidth": 0,
                    "maxLines": 0,
                    "letterSpacing": 0,
                    "chargeAfterEditing": false,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "textTransform": "none",
                    "widthFontSize": 0,
                    "textBox": false,
                    "shadowBlur": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0
                }
            }
        ]
    },
    {
        "title": "back",
        "thumbnail": "/Bildschirmfoto-2018-02-11-um-22.21.13.png",
        "options": {
            "stageWidth": 1100,
            "stageHeight": 800,
            "customAdds": {
                "uploads": true,
                "texts": true,
                "designs": true
            }
        },
        "mask": {
            "url": "/mask.svg",
            "left": "125",
            "top": "125"
        },
        "elements": [
            {
                "type": "image",
                "title": "Base",
                "source": "/BC-base-2.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "opacity": 1,
                    "removable": false,
                    "draggable": false,
                    "rotatable": false,
                    "resizable": false,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "inside",
                    "customAdds": []
                }
            },
            {
                "type": "text",
                "title": "YOURNAME",
                "source": "YOUR\\nNAME",
                "parameters": {
                    "left": 534,
                    "top": 401,
                    "angle": 0,
                    "price": 0,
                    "originX": "right",
                    "originY": "center",
                    "fill": "#000000",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "ABeeZee",
                    "fontSize": 39,
                    "minFontSize": 1,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "bold",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "right",
                    "maxLength": 0,
                    "maxLines": 0,
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "image",
                "title": "Line",
                "source": "/line.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": true,
                    "boundingBoxMode": "clipping",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "text",
                "title": "PHONE NUMBER COMPANY NAMEEMAIL ADDRESS",
                "source": "PHONE NUMBER \\nCOMPANY NAME\\nEMAIL ADDRESS",
                "parameters": {
                    "left": 573,
                    "top": 399,
                    "angle": 0,
                    "price": 0,
                    "originX": "left",
                    "originY": "center",
                    "fill": "#000000",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "ABeeZee",
                    "fontSize": 16,
                    "minFontSize": 1,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "left",
                    "maxLength": 0,
                    "maxLines": 0,
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "image",
                "title": "frame",
                "source": "/frame.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 0.96,
                    "scaleY": 0.93,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": true,
                    "boundingBoxMode": "clipping",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            }
        ]
    },
    {
        "title": "gold",
        "thumbnail": "/preview-gold-Kopie.png",
        "options": {
            "stageWidth": 1100,
            "stageHeight": 800,
            "customAdds": {
                "uploads": true,
                "texts": true,
                "designs": true
            }
        },
        "mask": {
            "url": "/mask.svg",
            "left": "125",
            "top": "125"
        },
        "elements": [
            {
                "type": "image",
                "title": "Base",
                "source": "/BC-base-2.png",
                "parameters": {
                    "locked": false,
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "opacity": 1,
                    "removable": false,
                    "draggable": false,
                    "rotatable": false,
                    "resizable": false,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "boundingBoxMode": "inside",
                    "customAdds": []
                }
            },
            {
                "type": "image",
                "title": "background",
                "source": "/background.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000,#ff0000,#008080,#0000ff,#800080",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "text",
                "title": "company",
                "source": "company",
                "parameters": {
                    "left": 791,
                    "top": 501,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000",
                    "fill": "#daa520",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": true,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "Graduate",
                    "fontSize": 67,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "widthFontSize": 0,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "left",
                    "maxLength": 0,
                    "maxLines": 0,
                    "stroke": "#ffffff",
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "image",
                "title": "ExLogo",
                "source": "/ExLogo.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "fill": "#daa520",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "inside",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "text",
                "title": "COMPANY",
                "source": "COMPANY",
                "parameters": {
                    "left": 309,
                    "top": 505,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000",
                    "fill": "#daa520",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "Graduate",
                    "fontSize": 67,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "widthFontSize": 0,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "left",
                    "maxLength": 0,
                    "maxLines": 0,
                    "stroke": "#ffffff",
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            }
        ]
    },
    {
        "title": "surf",
        "thumbnail": "/preview-surf-Kopie.png",
        "options": {
            "stageWidth": 1100,
            "stageHeight": 800,
            "customAdds": {
                "uploads": true,
                "texts": true,
                "designs": true
            }
        },
        "mask": {
            "url": "/mask.svg",
            "left": "125",
            "top": "125"
        },
        "elements": [
            {
                "type": "image",
                "title": "Base",
                "source": "/BC-base-2.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "opacity": 1,
                    "removable": false,
                    "draggable": false,
                    "rotatable": false,
                    "resizable": false,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "inside",
                    "customAdds": []
                }
            },
            {
                "type": "image",
                "title": "background",
                "source": "/background.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 550,
                    "top": 400,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000",
                    "fill": "#95d1d2",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "text",
                "title": "Hang Loose",
                "source": "Hang Loose",
                "parameters": {
                    "left": 682,
                    "top": 327,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000",
                    "fill": "#ffffff",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": true,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "Sacramento",
                    "fontSize": 106,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "widthFontSize": 0,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "left",
                    "maxLength": 0,
                    "maxLines": 0,
                    "stroke": "#ffffff",
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "image",
                "title": "surf logo",
                "source": "/surf-logo.png",
                "parameters": {
                    "uploadZone": false,
                    "left": 295,
                    "top": 387,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#3d4c4c",
                    "fill": "#3d4c4c",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "uniScalingUnlockable": false,
                    "excludeFromExport": false,
                    "advancedEditing": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            },
            {
                "type": "text",
                "title": "- Surf Shop -",
                "source": "- Surf Shop -",
                "parameters": {
                    "left": 801,
                    "top": 397,
                    "angle": 0,
                    "price": 0,
                    "originX": "center",
                    "originY": "center",
                    "colors": "#000000",
                    "fill": "#3d4c4c",
                    "opacity": 1,
                    "removable": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": false,
                    "topped": false,
                    "autoSelect": false,
                    "excludeFromExport": false,
                    "locked": false,
                    "boundingBoxMode": "clipping",
                    "fontFamily": "Text Me One",
                    "fontSize": 35,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "widthFontSize": 0,
                    "lineHeight": 1,
                    "letterSpacing": 0,
                    "editable": true,
                    "chargeAfterEditing": false,
                    "fontWeight": "normal",
                    "fontStyle": "normal",
                    "textDecoration": "normal",
                    "textTransform": "none",
                    "textAlign": "left",
                    "maxLength": 0,
                    "maxLines": 0,
                    "stroke": "#ffffff",
                    "strokeWidth": 0,
                    "curvable": false,
                    "curved": false,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "textBox": false,
                    "customAdds": [],
                    "boundingBox": "Base"
                }
            }
        ]
    }
]
const businessCardJSON = [
    [
        {
            "productTitle": "Business Card Slim",
            "title": "front",
            "thumbnail": "/Bildschirmfoto-2018-02-11-um-22.21.01.png",
            "options": {
                "stageWidth": 1100,
                "stageHeight": 800
            },
            "elements": [
                {
                    "title": "Base",
                    "source": "/BC-base-2.png",
                    "type": "image",
                    "parameters": {
                        "left": 550,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": false,
                        "colorLinkGroup": false,
                        "draggable": false,
                        "rotatable": false,
                        "resizable": false,
                        "removable": false,
                        "flipX": false,
                        "flipY": false,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": false,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "inside",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "",
                        "resizeToW": "0",
                        "resizeToH": "0",
                        "scaleMode": "fit",
                        "minScaleLimit": 0.01,
                        "advancedEditing": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "customAdds": []
                    }
                },
                {
                    "title": "background",
                    "source": "/background.png",
                    "type": "image",
                    "parameters": {
                        "left": 550,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": false,
                        "colors": "#000000, #ff0000, #008080, #0000ff, #800080",
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "flipX": false,
                        "flipY": false,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": false,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "",
                        "resizeToW": "0",
                        "resizeToH": "0",
                        "scaleMode": "fit",
                        "minScaleLimit": 0.01,
                        "advancedEditing": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "customAdds": []
                    }
                },
                {
                    "title": "COMPANY NAME",
                    "source": "COMPANY NAME",
                    "type": "text",
                    "parameters": {
                        "left": 550,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": "#ffffff",
                        "colors": "#000000",
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "flipX": false,
                        "flipY": false,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": true,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "Base",
                        "fontFamily": "Aller",
                        "fontSize": 98,
                        "editable": true,
                        "lineHeight": 1,
                        "textDecoration": "normal",
                        "maxLength": 0,
                        "fontWeight": "normal",
                        "fontStyle": "normal",
                        "textAlign": "left",
                        "curvable": false,
                        "curved": false,
                        "curveSpacing": 10,
                        "curveRadius": 80,
                        "curveReverse": false,
                        "stroke": "#ffffff",
                        "strokeWidth": 0,
                        "maxLines": 0,
                        "letterSpacing": 0,
                        "chargeAfterEditing": false,
                        "minFontSize": 1,
                        "maxFontSize": 1000,
                        "textTransform": "none",
                        "widthFontSize": 0,
                        "textBox": false,
                        "shadowBlur": 0,
                        "shadowOffsetX": 0,
                        "shadowOffsetY": 0
                    }
                }
            ]
        },
        {
            "title": "back",
            "thumbnail": "/Bildschirmfoto-2018-02-11-um-22.21.13.png",
            "options": {
                "stageWidth": 1100,
                "stageHeight": 800
            },
            "elements": [
                {
                    "title": "Base",
                    "source": "/BC-base-2.png",
                    "type": "image",
                    "parameters": {
                        "left": 550,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": false,
                        "colorLinkGroup": false,
                        "draggable": false,
                        "rotatable": false,
                        "resizable": false,
                        "removable": false,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": false,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "inside",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "0",
                        "resizeToW": "0",
                        "resizeToH": "0",
                        "filter": false,
                        "scaleMode": "fit",
                        "minScaleLimit": 0.01,
                        "advancedEditing": false,
                        "uploadZone": false,
                        "customAdds": []
                    }
                },
                {
                    "title": "YOURNAME",
                    "source": "YOUR NAME",
                    "type": "text",
                    "parameters": {
                        "left": 534,
                        "top": 401,
                        "originX": "right",
                        "originY": "center",
                        "z": -1,
                        "fill": "#000000",
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": true,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "Base",
                        "fontFamily": "ABeeZee",
                        "fontSize": 39,
                        "editable": true,
                        "lineHeight": 1,
                        "textDecoration": "normal",
                        "maxLength": 0,
                        "fontWeight": "bold",
                        "fontStyle": "normal",
                        "textAlign": "right",
                        "curvable": false,
                        "curved": false,
                        "curveSpacing": 10,
                        "curveRadius": 80,
                        "curveReverse": false,
                        "stroke": "0",
                        "strokeWidth": 0,
                        "maxLines": 0,
                        "letterSpacing": 0,
                        "chargeAfterEditing": false,
                        "minFontSize": 1,
                        "maxFontSize": 1000,
                        "textTransform": "none",
                        "widthFontSize": 0,
                        "textBox": false,
                        "shadowBlur": 0,
                        "shadowOffsetX": 0,
                        "shadowOffsetY": 0
                    }
                },
                {
                    "title": "Line",
                    "source": "/line.png",
                    "type": "image",
                    "parameters": {
                        "left": 550,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": false,
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": false,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": true,
                        "showInColorSelection": false,
                        "boundingBox": "Base",
                        "resizeToW": "0",
                        "resizeToH": "0",
                        "filter": false,
                        "scaleMode": "fit",
                        "minScaleLimit": 0.01,
                        "advancedEditing": false,
                        "uploadZone": false,
                        "customAdds": []
                    }
                },
                {
                    "title": "PHONE NUMBER COMPANY NAMEEMAIL ADDRESS",
                    "source": "PHONE NUMBER COMPANY NAME EMAIL ADDRESS",
                    "type": "text",
                    "parameters": {
                        "left": 567,
                        "top": 399,
                        "originX": "left",
                        "originY": "center",
                        "z": -1,
                        "fill": "#000000",
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "zChangeable": false,
                        "scaleX": 1,
                        "scaleY": 1,
                        "lockUniScaling": true,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": false,
                        "showInColorSelection": false,
                        "boundingBox": "Base",
                        "fontFamily": "ABeeZee",
                        "fontSize": 16,
                        "editable": true,
                        "lineHeight": 1,
                        "textDecoration": "normal",
                        "maxLength": 0,
                        "fontWeight": "normal",
                        "fontStyle": "normal",
                        "textAlign": "left",
                        "curvable": false,
                        "curved": false,
                        "curveSpacing": 10,
                        "curveRadius": 80,
                        "curveReverse": false,
                        "stroke": "0",
                        "strokeWidth": 0,
                        "maxLines": 0,
                        "letterSpacing": 0,
                        "chargeAfterEditing": false,
                        "minFontSize": 1,
                        "maxFontSize": 1000,
                        "textTransform": "none",
                        "widthFontSize": 0,
                        "textBox": false,
                        "shadowBlur": 0,
                        "shadowOffsetX": 0,
                        "shadowOffsetY": 0
                    }
                },
                {
                    "title": "frame",
                    "source": "/frame.png",
                    "type": "image",
                    "parameters": {
                        "left": 549,
                        "top": 400,
                        "originX": "center",
                        "originY": "center",
                        "z": -1,
                        "fill": false,
                        "colorLinkGroup": false,
                        "draggable": true,
                        "rotatable": true,
                        "resizable": true,
                        "removable": true,
                        "zChangeable": false,
                        "scaleX": 0.96,
                        "scaleY": 0.93,
                        "lockUniScaling": false,
                        "uniScalingUnlockable": false,
                        "angle": 0,
                        "price": 0,
                        "autoCenter": false,
                        "replaceInAllViews": false,
                        "autoSelect": false,
                        "topped": false,
                        "boundingBoxMode": "clipping",
                        "opacity": 1,
                        "excludeFromExport": false,
                        "locked": true,
                        "showInColorSelection": false,
                        "boundingBox": "Base",
                        "resizeToW": "0",
                        "resizeToH": "0",
                        "filter": false,
                        "scaleMode": "fit",
                        "minScaleLimit": 0.01,
                        "advancedEditing": false,
                        "uploadZone": false,
                        "customAdds": []
                    }
                }
            ]
        }
    ]
]

console.log(businessCardJSON);

const fpd = new FancyProductDesigner(document.getElementById("fpd-target"), {
  productsJSON: businessCardJSON,
  layouts: businessCardLayoutJSON,
  mainBarModules: [
      'layouts',
      'images',
      'text',
  ],
  customImageParameters: {
      removable: true,
      draggable: true,
      resizable: true,
      autoCenter: true,
      price: 10,
      maxSize: 10,
      autoSelect: true,
      advancedEditing: true
  },
  customTextParameters: {
      autoCenter: true,
      draggable: true,
      removable: true,
      colors: true,
  },
  textTemplates: [
      {
          text: "Text Template Content",
          properties: {
              fontSize: 30,
              fontFamily: "Lobster"
          }
      },
      {
          text: "Another Text Template",
          properties: {
              fontSize: 50,
              fontFamily: "Pacifico"
          }
      }
  ],
});
console.log(fpd);

fpd.addEventListener("ready", () => {
  console.log("ready");
});
